import './globals.css'
import styles from './page.module.css'
export const metadata = {
  title: 'Caleb Cooper',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
